service: lottery-planner
provider:
  name: aws
  runtime: nodejs4.3
  # stage: dev
  region: eu-central-1
  #memorySize: 1024 # tests have shown that more than 64 is never used

functions:
  planner:
    handler: index.planner # file and module; required, handler set in AWS Lambda
    events:
      # http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
      - schedule:
          name: lucky-number-generator
          description: Selects a weekly random number as a winner
          # enabled: true -- enabled by default
          # cron expressions are UTC-based
          # http://docs.aws.amazon.com/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html
          rate: cron(0 12 ? * SAT *) # run at 12pm each Saturday
